### ISSUE TITLE
first connection

### ISSUE THREAD

**Issue by elviskudo** [stitchng/adonis-sse#1]
Hi stitch,

Please, give me an example:
how to do:
- connect from stream to my html5 frontend
- send my custom stream to my html5

thanks, youre awesome

**Comment by stitchng** [comment]
Hello @elviskudo ,

Kindly go through the [instructions markdown file](https://github.com/stitchng/adonis-sse/blob/master/instructions.md) to see how to setup your provider(s) / middleware(s).

After you are done with the above, simply create a _"stream"_ route and a view route inside your project's `start/routes.js` file like so:

```js

/** @type {typeof import('@adonisjs/framework/src/Route/Manager')} */
const Route = use('Route');

Route.get('/timing', ({ source }) => {
      setTimeout(function(){
           source.send({ data: true, timing:Date.now() },  '!This is a comment!');
      }, 1000);
}).as('timing')//.middleware(['eventsource']);

Route.get('/page/events', ({ view }) => {
  return view.render('events')
}).as('event-page');

```

>On the client side (HTML5 Web Front-End), use the `EventSource`  constructor to setup a connection to the **AdonisJS** server which is by default is served on host 127.0.0.1 (localhost) and port 3333. See the [docs](https://adonisjs.com/docs/4.0/installation#_running_application) for more info on _Running An AdonisJS Application_.

Next you create an AdonisJS view file in the `resources/views/events.edge`

```html 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Event Stream</title>
    <meta name="description" content="A server-sent events demo" />
    <meta name="author" content="stitchng">
</head>
<body id="page">
<ul id="stream-list"></ul>
<script type="text/javascript">
 var eventSource = new EventSource("{{ route('timing') }}");

eventSource.onopen = function(e){
 console.log("Connected: A server connection has been established");
};

eventSource.onerror = function(e){
   //alert("Couldn't Connect: An error occurred with the server event stream!");
   switch (e.target.readyState) {

        case EventSource.CONNECTING:
            console.log('Reconnecting...');
            break;

        case EventSource.CLOSED:
            console.log('Connection failed, will not reconnect');
            break;

    }
};

eventSource.onmessage = function(e){
   console.log("Origin Server Address: ", e.origin);
   console.log("Last event Id: ", e.lastEventId);

   var newElement = document.createElement("li");
   var eventList = document.getElementById("stream-list");
  newElement.textContent = "new message from server: " + e.data;
  eventList.appendChild(newElement);
};
</script>
</body>
</html>

```

Finally, load the page _https://127.0.0.1:3333/page/events_ on your browser address bar and in a couple of seconds you should see items appearing on the screen and logs on the console of the browser as well.

**Comment by elviskudo** [comment]
oh thanks yo man,

but i already implemented that in my local,
but result is ```Connection failed, will not reconnect``` in my console
server running

am i miss something

and what about if, i throw my data from other route, then shown up in browser
sorry my english is not good

thanks a lot btw

**Comment by stitchng** [comment]
Hello @elviskudo 

I will like to have screenshots of the following file(s) opened in a code editor:

1. _start/kernel.js_
2. _start/app.js_
3. _start/routes.js_

And finally a screenshot of the **AdonisJS** console (looking for possible NodeJS errors here)  as soon as the browser logs: `Connection failed, will not reconnect`

Thanks

**Comment by stitchng** [comment]
Are you sure you registered the provider(s) and middleware(s) also ?

**Comment by elviskudo** [comment]
start/app.js
```
const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/framework/providers/ViewProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  '@adonisjs/bodyparser/providers/BodyParserProvider',
  '@adonisjs/cors/providers/CorsProvider',
  '@adonisjs/shield/providers/ShieldProvider',
  '@adonisjs/session/providers/SessionProvider',
  '@adonisjs/auth/providers/AuthProvider',
  '@adonisjs/mail/providers/MailProvider',
  'adonisjs-sse/providers/ServerSentEventsProvider',
]
```

start/kernel.js
```
const namedMiddleware = {
  auth: 'Adonis/Middleware/Auth',
  guest: 'Adonis/Middleware/AllowGuestOnly',
  eventsource: 'Adonis/Middleware/EventSourceWatcher'
}
```

start/routes.js
```
Route.get('/timing', ({ source }) => {
    setTimeout(function() {
        const data = { data: true, timing: Date.now() }
        source.send(data, '!This is a comment!');
    }, 1000);
}).as('timing')//.middleware(['eventsource']);

Route.get('/page/events', ({ view }) => {
    return view.render('events')
}).as('event-page');
```

**Comment by stitchng** [comment]
You have a problem in your `start/routes.js` file

Update it to look exactly like this:

```js

Route.get('/timing', ({ source }) => {
    setTimeout(function() {
        const data = { data: true, timing: Date.now() }
        source.send(data, '!This is a comment!');
    }, 1000);
}).as('timing').middleware(['eventsource']);

Route.get('/page/events', ({ view }) => {
    return view.render('events')
}).as('event-page');
```

Copy and paste from here if you like.

**Comment by isocroft** [comment]
@elviskudo Hey man, did you get this to work for you ?

**Comment by elviskudo** [comment]
ok, thanks man
i'll try later, now i close this issue
